repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9  # versión actual de Ruff
    hooks:
      - id: ruff
        args: [--fix]   # aplica correcciones automáticas cuando sea posible
      - id: ruff-format # formateo (equivalente a black)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
